// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoOrderStyleFileInfo.proto

package com.kingthy.proto;

public final class ProtoOrderStyleFileInfo {
  private ProtoOrderStyleFileInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code EUnit}
   */
  public enum EUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EUnit_m = 0;</code>
     *
     * <pre>
     *米
     * </pre>
     */
    EUnit_m(0, 0),
    /**
     * <code>EUnit_g = 1;</code>
     *
     * <pre>
     *个
     * </pre>
     */
    EUnit_g(1, 1),
    /**
     * <code>EUnit_l = 2;</code>
     *
     * <pre>
     *粒
     * </pre>
     */
    EUnit_l(2, 2),
    ;

    /**
     * <code>EUnit_m = 0;</code>
     *
     * <pre>
     *米
     * </pre>
     */
    public static final int EUnit_m_VALUE = 0;
    /**
     * <code>EUnit_g = 1;</code>
     *
     * <pre>
     *个
     * </pre>
     */
    public static final int EUnit_g_VALUE = 1;
    /**
     * <code>EUnit_l = 2;</code>
     *
     * <pre>
     *粒
     * </pre>
     */
    public static final int EUnit_l_VALUE = 2;


    public final int getNumber() { return value; }

    public static EUnit valueOf(int value) {
      switch (value) {
        case 0: return EUnit_m;
        case 1: return EUnit_g;
        case 2: return EUnit_l;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EUnit>() {
            public EUnit findValueByNumber(int number) {
              return EUnit.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtoOrderStyleFileInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final EUnit[] VALUES = values();

    public static EUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EUnit)
  }

  public interface OrderStyleFileInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string order_item_sn = 1;
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    boolean hasOrderItemSn();
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    String getOrderItemSn();
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderItemSnBytes();

    // repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    java.util.List<OrderStyleFileInfo.StyleFile>
        getOrderStyleList();
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    OrderStyleFileInfo.StyleFile getOrderStyle(int index);
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    int getOrderStyleCount();
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    java.util.List<? extends OrderStyleFileInfo.StyleFileOrBuilder>
        getOrderStyleOrBuilderList();
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    OrderStyleFileInfo.StyleFileOrBuilder getOrderStyleOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code OrderStyleFileInfo}
   *
   * <pre>
   *款式文件接口表
   * </pre>
   */
  public static final class OrderStyleFileInfo extends
      com.google.protobuf.GeneratedMessage
      implements OrderStyleFileInfoOrBuilder {
    // Use OrderStyleFileInfo.newBuilder() to construct.
    private OrderStyleFileInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderStyleFileInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderStyleFileInfo defaultInstance;
    public static OrderStyleFileInfo getDefaultInstance() {
      return defaultInstance;
    }

    public OrderStyleFileInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderStyleFileInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orderItemSn_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                orderStyle_ = new java.util.ArrayList<StyleFile>();
                mutable_bitField0_ |= 0x00000002;
              }
              orderStyle_.add(input.readMessage(StyleFile.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          orderStyle_ = java.util.Collections.unmodifiableList(orderStyle_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderStyleFileInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<OrderStyleFileInfo> PARSER =
        new com.google.protobuf.AbstractParser<OrderStyleFileInfo>() {
      public OrderStyleFileInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderStyleFileInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OrderStyleFileInfo> getParserForType() {
      return PARSER;
    }

    public interface StyleFileOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string style_code = 1;
      /**
       * <code>required string style_code = 1;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      boolean hasStyleCode();
      /**
       * <code>required string style_code = 1;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      String getStyleCode();
      /**
       * <code>required string style_code = 1;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getStyleCodeBytes();

      // required string material_code = 2;
      /**
       * <code>required string material_code = 2;</code>
       *
       * <pre>
       *物料编码
       * </pre>
       */
      boolean hasMaterialCode();
      /**
       * <code>required string material_code = 2;</code>
       *
       * <pre>
       *物料编码
       * </pre>
       */
      String getMaterialCode();
      /**
       * <code>required string material_code = 2;</code>
       *
       * <pre>
       *物料编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getMaterialCodeBytes();

      // required float breadth = 3;
      /**
       * <code>required float breadth = 3;</code>
       *
       * <pre>
       *幅宽
       * </pre>
       */
      boolean hasBreadth();
      /**
       * <code>required float breadth = 3;</code>
       *
       * <pre>
       *幅宽
       * </pre>
       */
      float getBreadth();

      // required int32 quantity = 4;
      /**
       * <code>required int32 quantity = 4;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      boolean hasQuantity();
      /**
       * <code>required int32 quantity = 4;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      int getQuantity();

      // required .EUnit unit = 5;
      /**
       * <code>required .EUnit unit = 5;</code>
       *
       * <pre>
       *数量单位（仿真给到几何）
       * </pre>
       */
      boolean hasUnit();
      /**
       * <code>required .EUnit unit = 5;</code>
       *
       * <pre>
       *数量单位（仿真给到几何）
       * </pre>
       */
      EUnit getUnit();

      // required float acreage = 6;
      /**
       * <code>required float acreage = 6;</code>
       *
       * <pre>
       *面积(暂时为空） 
       * </pre>
       */
      boolean hasAcreage();
      /**
       * <code>required float acreage = 6;</code>
       *
       * <pre>
       *面积(暂时为空） 
       * </pre>
       */
      float getAcreage();

      // required string plt_path = 7;
      /**
       * <code>required string plt_path = 7;</code>
       *
       * <pre>
       *纸样PLT文件路径
       * </pre>
       */
      boolean hasPltPath();
      /**
       * <code>required string plt_path = 7;</code>
       *
       * <pre>
       *纸样PLT文件路径
       * </pre>
       */
      String getPltPath();
      /**
       * <code>required string plt_path = 7;</code>
       *
       * <pre>
       *纸样PLT文件路径
       * </pre>
       */
      com.google.protobuf.ByteString
          getPltPathBytes();
    }
    /**
     * Protobuf type {@code OrderStyleFileInfo.StyleFile}
     */
    public static final class StyleFile extends
        com.google.protobuf.GeneratedMessage
        implements StyleFileOrBuilder {
      // Use StyleFile.newBuilder() to construct.
      private StyleFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private StyleFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final StyleFile defaultInstance;
      public static StyleFile getDefaultInstance() {
        return defaultInstance;
      }

      public StyleFile getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private StyleFile(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                styleCode_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                materialCode_ = input.readBytes();
                break;
              }
              case 29: {
                bitField0_ |= 0x00000004;
                breadth_ = input.readFloat();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                quantity_ = input.readInt32();
                break;
              }
              case 40: {
                int rawValue = input.readEnum();
                EUnit value = EUnit.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(5, rawValue);
                } else {
                  bitField0_ |= 0x00000010;
                  unit_ = value;
                }
                break;
              }
              case 53: {
                bitField0_ |= 0x00000020;
                acreage_ = input.readFloat();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                pltPath_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_StyleFile_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_StyleFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StyleFile.class, Builder.class);
      }

      public static com.google.protobuf.Parser<StyleFile> PARSER =
          new com.google.protobuf.AbstractParser<StyleFile>() {
        public StyleFile parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new StyleFile(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<StyleFile> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string style_code = 1;
      public static final int STYLE_CODE_FIELD_NUMBER = 1;
      private Object styleCode_;
      /**
       * <code>required string style_code = 1;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      public boolean hasStyleCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string style_code = 1;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      public String getStyleCode() {
        Object ref = styleCode_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            styleCode_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string style_code = 1;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStyleCodeBytes() {
        Object ref = styleCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          styleCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string material_code = 2;
      public static final int MATERIAL_CODE_FIELD_NUMBER = 2;
      private Object materialCode_;
      /**
       * <code>required string material_code = 2;</code>
       *
       * <pre>
       *物料编码
       * </pre>
       */
      public boolean hasMaterialCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string material_code = 2;</code>
       *
       * <pre>
       *物料编码
       * </pre>
       */
      public String getMaterialCode() {
        Object ref = materialCode_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            materialCode_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string material_code = 2;</code>
       *
       * <pre>
       *物料编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMaterialCodeBytes() {
        Object ref = materialCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          materialCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required float breadth = 3;
      public static final int BREADTH_FIELD_NUMBER = 3;
      private float breadth_;
      /**
       * <code>required float breadth = 3;</code>
       *
       * <pre>
       *幅宽
       * </pre>
       */
      public boolean hasBreadth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float breadth = 3;</code>
       *
       * <pre>
       *幅宽
       * </pre>
       */
      public float getBreadth() {
        return breadth_;
      }

      // required int32 quantity = 4;
      public static final int QUANTITY_FIELD_NUMBER = 4;
      private int quantity_;
      /**
       * <code>required int32 quantity = 4;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 quantity = 4;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public int getQuantity() {
        return quantity_;
      }

      // required .EUnit unit = 5;
      public static final int UNIT_FIELD_NUMBER = 5;
      private EUnit unit_;
      /**
       * <code>required .EUnit unit = 5;</code>
       *
       * <pre>
       *数量单位（仿真给到几何）
       * </pre>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .EUnit unit = 5;</code>
       *
       * <pre>
       *数量单位（仿真给到几何）
       * </pre>
       */
      public EUnit getUnit() {
        return unit_;
      }

      // required float acreage = 6;
      public static final int ACREAGE_FIELD_NUMBER = 6;
      private float acreage_;
      /**
       * <code>required float acreage = 6;</code>
       *
       * <pre>
       *面积(暂时为空） 
       * </pre>
       */
      public boolean hasAcreage() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float acreage = 6;</code>
       *
       * <pre>
       *面积(暂时为空） 
       * </pre>
       */
      public float getAcreage() {
        return acreage_;
      }

      // required string plt_path = 7;
      public static final int PLT_PATH_FIELD_NUMBER = 7;
      private Object pltPath_;
      /**
       * <code>required string plt_path = 7;</code>
       *
       * <pre>
       *纸样PLT文件路径
       * </pre>
       */
      public boolean hasPltPath() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string plt_path = 7;</code>
       *
       * <pre>
       *纸样PLT文件路径
       * </pre>
       */
      public String getPltPath() {
        Object ref = pltPath_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pltPath_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string plt_path = 7;</code>
       *
       * <pre>
       *纸样PLT文件路径
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPltPathBytes() {
        Object ref = pltPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pltPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        styleCode_ = "";
        materialCode_ = "";
        breadth_ = 0F;
        quantity_ = 0;
        unit_ = EUnit.EUnit_m;
        acreage_ = 0F;
        pltPath_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasStyleCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMaterialCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBreadth()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasQuantity()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUnit()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAcreage()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPltPath()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getStyleCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getMaterialCodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeFloat(3, breadth_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, quantity_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeEnum(5, unit_.getNumber());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeFloat(6, acreage_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, getPltPathBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getStyleCodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMaterialCodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, breadth_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, quantity_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(5, unit_.getNumber());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(6, acreage_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, getPltPathBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static StyleFile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static StyleFile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static StyleFile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static StyleFile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static StyleFile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static StyleFile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static StyleFile parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static StyleFile parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static StyleFile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static StyleFile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(StyleFile prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code OrderStyleFileInfo.StyleFile}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements StyleFileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_StyleFile_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_StyleFile_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  StyleFile.class, Builder.class);
        }

        // Construct using com.kingthy.proto.ProtoOrderStyleFileInfo.OrderStyleFileInfo.StyleFile.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          styleCode_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          materialCode_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          breadth_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000004);
          quantity_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          unit_ = EUnit.EUnit_m;
          bitField0_ = (bitField0_ & ~0x00000010);
          acreage_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000020);
          pltPath_ = "";
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_StyleFile_descriptor;
        }

        public StyleFile getDefaultInstanceForType() {
          return StyleFile.getDefaultInstance();
        }

        public StyleFile build() {
          StyleFile result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public StyleFile buildPartial() {
          StyleFile result = new StyleFile(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.styleCode_ = styleCode_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.materialCode_ = materialCode_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.breadth_ = breadth_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.quantity_ = quantity_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.unit_ = unit_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.acreage_ = acreage_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.pltPath_ = pltPath_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof StyleFile) {
            return mergeFrom((StyleFile)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(StyleFile other) {
          if (other == StyleFile.getDefaultInstance()) return this;
          if (other.hasStyleCode()) {
            bitField0_ |= 0x00000001;
            styleCode_ = other.styleCode_;
            onChanged();
          }
          if (other.hasMaterialCode()) {
            bitField0_ |= 0x00000002;
            materialCode_ = other.materialCode_;
            onChanged();
          }
          if (other.hasBreadth()) {
            setBreadth(other.getBreadth());
          }
          if (other.hasQuantity()) {
            setQuantity(other.getQuantity());
          }
          if (other.hasUnit()) {
            setUnit(other.getUnit());
          }
          if (other.hasAcreage()) {
            setAcreage(other.getAcreage());
          }
          if (other.hasPltPath()) {
            bitField0_ |= 0x00000040;
            pltPath_ = other.pltPath_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasStyleCode()) {
            
            return false;
          }
          if (!hasMaterialCode()) {
            
            return false;
          }
          if (!hasBreadth()) {
            
            return false;
          }
          if (!hasQuantity()) {
            
            return false;
          }
          if (!hasUnit()) {
            
            return false;
          }
          if (!hasAcreage()) {
            
            return false;
          }
          if (!hasPltPath()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          StyleFile parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (StyleFile) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string style_code = 1;
        private Object styleCode_ = "";
        /**
         * <code>required string style_code = 1;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public boolean hasStyleCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string style_code = 1;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public String getStyleCode() {
          Object ref = styleCode_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            styleCode_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string style_code = 1;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getStyleCodeBytes() {
          Object ref = styleCode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            styleCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string style_code = 1;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public Builder setStyleCode(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          styleCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string style_code = 1;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public Builder clearStyleCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          styleCode_ = getDefaultInstance().getStyleCode();
          onChanged();
          return this;
        }
        /**
         * <code>required string style_code = 1;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public Builder setStyleCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          styleCode_ = value;
          onChanged();
          return this;
        }

        // required string material_code = 2;
        private Object materialCode_ = "";
        /**
         * <code>required string material_code = 2;</code>
         *
         * <pre>
         *物料编码
         * </pre>
         */
        public boolean hasMaterialCode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string material_code = 2;</code>
         *
         * <pre>
         *物料编码
         * </pre>
         */
        public String getMaterialCode() {
          Object ref = materialCode_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            materialCode_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string material_code = 2;</code>
         *
         * <pre>
         *物料编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getMaterialCodeBytes() {
          Object ref = materialCode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            materialCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string material_code = 2;</code>
         *
         * <pre>
         *物料编码
         * </pre>
         */
        public Builder setMaterialCode(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          materialCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string material_code = 2;</code>
         *
         * <pre>
         *物料编码
         * </pre>
         */
        public Builder clearMaterialCode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          materialCode_ = getDefaultInstance().getMaterialCode();
          onChanged();
          return this;
        }
        /**
         * <code>required string material_code = 2;</code>
         *
         * <pre>
         *物料编码
         * </pre>
         */
        public Builder setMaterialCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          materialCode_ = value;
          onChanged();
          return this;
        }

        // required float breadth = 3;
        private float breadth_ ;
        /**
         * <code>required float breadth = 3;</code>
         *
         * <pre>
         *幅宽
         * </pre>
         */
        public boolean hasBreadth() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required float breadth = 3;</code>
         *
         * <pre>
         *幅宽
         * </pre>
         */
        public float getBreadth() {
          return breadth_;
        }
        /**
         * <code>required float breadth = 3;</code>
         *
         * <pre>
         *幅宽
         * </pre>
         */
        public Builder setBreadth(float value) {
          bitField0_ |= 0x00000004;
          breadth_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float breadth = 3;</code>
         *
         * <pre>
         *幅宽
         * </pre>
         */
        public Builder clearBreadth() {
          bitField0_ = (bitField0_ & ~0x00000004);
          breadth_ = 0F;
          onChanged();
          return this;
        }

        // required int32 quantity = 4;
        private int quantity_ ;
        /**
         * <code>required int32 quantity = 4;</code>
         *
         * <pre>
         *数量
         * </pre>
         */
        public boolean hasQuantity() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int32 quantity = 4;</code>
         *
         * <pre>
         *数量
         * </pre>
         */
        public int getQuantity() {
          return quantity_;
        }
        /**
         * <code>required int32 quantity = 4;</code>
         *
         * <pre>
         *数量
         * </pre>
         */
        public Builder setQuantity(int value) {
          bitField0_ |= 0x00000008;
          quantity_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 quantity = 4;</code>
         *
         * <pre>
         *数量
         * </pre>
         */
        public Builder clearQuantity() {
          bitField0_ = (bitField0_ & ~0x00000008);
          quantity_ = 0;
          onChanged();
          return this;
        }

        // required .EUnit unit = 5;
        private EUnit unit_ = EUnit.EUnit_m;
        /**
         * <code>required .EUnit unit = 5;</code>
         *
         * <pre>
         *数量单位（仿真给到几何）
         * </pre>
         */
        public boolean hasUnit() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required .EUnit unit = 5;</code>
         *
         * <pre>
         *数量单位（仿真给到几何）
         * </pre>
         */
        public EUnit getUnit() {
          return unit_;
        }
        /**
         * <code>required .EUnit unit = 5;</code>
         *
         * <pre>
         *数量单位（仿真给到几何）
         * </pre>
         */
        public Builder setUnit(EUnit value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          unit_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .EUnit unit = 5;</code>
         *
         * <pre>
         *数量单位（仿真给到几何）
         * </pre>
         */
        public Builder clearUnit() {
          bitField0_ = (bitField0_ & ~0x00000010);
          unit_ = EUnit.EUnit_m;
          onChanged();
          return this;
        }

        // required float acreage = 6;
        private float acreage_ ;
        /**
         * <code>required float acreage = 6;</code>
         *
         * <pre>
         *面积(暂时为空） 
         * </pre>
         */
        public boolean hasAcreage() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required float acreage = 6;</code>
         *
         * <pre>
         *面积(暂时为空） 
         * </pre>
         */
        public float getAcreage() {
          return acreage_;
        }
        /**
         * <code>required float acreage = 6;</code>
         *
         * <pre>
         *面积(暂时为空） 
         * </pre>
         */
        public Builder setAcreage(float value) {
          bitField0_ |= 0x00000020;
          acreage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float acreage = 6;</code>
         *
         * <pre>
         *面积(暂时为空） 
         * </pre>
         */
        public Builder clearAcreage() {
          bitField0_ = (bitField0_ & ~0x00000020);
          acreage_ = 0F;
          onChanged();
          return this;
        }

        // required string plt_path = 7;
        private Object pltPath_ = "";
        /**
         * <code>required string plt_path = 7;</code>
         *
         * <pre>
         *纸样PLT文件路径
         * </pre>
         */
        public boolean hasPltPath() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required string plt_path = 7;</code>
         *
         * <pre>
         *纸样PLT文件路径
         * </pre>
         */
        public String getPltPath() {
          Object ref = pltPath_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            pltPath_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string plt_path = 7;</code>
         *
         * <pre>
         *纸样PLT文件路径
         * </pre>
         */
        public com.google.protobuf.ByteString
            getPltPathBytes() {
          Object ref = pltPath_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            pltPath_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string plt_path = 7;</code>
         *
         * <pre>
         *纸样PLT文件路径
         * </pre>
         */
        public Builder setPltPath(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          pltPath_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string plt_path = 7;</code>
         *
         * <pre>
         *纸样PLT文件路径
         * </pre>
         */
        public Builder clearPltPath() {
          bitField0_ = (bitField0_ & ~0x00000040);
          pltPath_ = getDefaultInstance().getPltPath();
          onChanged();
          return this;
        }
        /**
         * <code>required string plt_path = 7;</code>
         *
         * <pre>
         *纸样PLT文件路径
         * </pre>
         */
        public Builder setPltPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          pltPath_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:OrderStyleFileInfo.StyleFile)
      }

      static {
        defaultInstance = new StyleFile(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:OrderStyleFileInfo.StyleFile)
    }

    private int bitField0_;
    // required string order_item_sn = 1;
    public static final int ORDER_ITEM_SN_FIELD_NUMBER = 1;
    private Object orderItemSn_;
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    public boolean hasOrderItemSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    public String getOrderItemSn() {
      Object ref = orderItemSn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderItemSn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderItemSnBytes() {
      Object ref = orderItemSn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderItemSn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;
    public static final int ORDERSTYLE_FIELD_NUMBER = 2;
    private java.util.List<StyleFile> orderStyle_;
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    public java.util.List<StyleFile> getOrderStyleList() {
      return orderStyle_;
    }
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    public java.util.List<? extends StyleFileOrBuilder>
        getOrderStyleOrBuilderList() {
      return orderStyle_;
    }
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    public int getOrderStyleCount() {
      return orderStyle_.size();
    }
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    public StyleFile getOrderStyle(int index) {
      return orderStyle_.get(index);
    }
    /**
     * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
     *
     * <pre>
     *款式文件
     * </pre>
     */
    public StyleFileOrBuilder getOrderStyleOrBuilder(
        int index) {
      return orderStyle_.get(index);
    }

    private void initFields() {
      orderItemSn_ = "";
      orderStyle_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOrderItemSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOrderStyleCount(); i++) {
        if (!getOrderStyle(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOrderItemSnBytes());
      }
      for (int i = 0; i < orderStyle_.size(); i++) {
        output.writeMessage(2, orderStyle_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderItemSnBytes());
      }
      for (int i = 0; i < orderStyle_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, orderStyle_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static OrderStyleFileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderStyleFileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderStyleFileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderStyleFileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderStyleFileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OrderStyleFileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static OrderStyleFileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static OrderStyleFileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static OrderStyleFileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OrderStyleFileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(OrderStyleFileInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderStyleFileInfo}
     *
     * <pre>
     *款式文件接口表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OrderStyleFileInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderStyleFileInfo.class, Builder.class);
      }

      // Construct using com.kingthy.proto.ProtoOrderStyleFileInfo.OrderStyleFileInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOrderStyleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orderItemSn_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (orderStyleBuilder_ == null) {
          orderStyle_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          orderStyleBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoOrderStyleFileInfo.internal_static_OrderStyleFileInfo_descriptor;
      }

      public OrderStyleFileInfo getDefaultInstanceForType() {
        return OrderStyleFileInfo.getDefaultInstance();
      }

      public OrderStyleFileInfo build() {
        OrderStyleFileInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OrderStyleFileInfo buildPartial() {
        OrderStyleFileInfo result = new OrderStyleFileInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderItemSn_ = orderItemSn_;
        if (orderStyleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            orderStyle_ = java.util.Collections.unmodifiableList(orderStyle_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.orderStyle_ = orderStyle_;
        } else {
          result.orderStyle_ = orderStyleBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderStyleFileInfo) {
          return mergeFrom((OrderStyleFileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderStyleFileInfo other) {
        if (other == OrderStyleFileInfo.getDefaultInstance()) return this;
        if (other.hasOrderItemSn()) {
          bitField0_ |= 0x00000001;
          orderItemSn_ = other.orderItemSn_;
          onChanged();
        }
        if (orderStyleBuilder_ == null) {
          if (!other.orderStyle_.isEmpty()) {
            if (orderStyle_.isEmpty()) {
              orderStyle_ = other.orderStyle_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOrderStyleIsMutable();
              orderStyle_.addAll(other.orderStyle_);
            }
            onChanged();
          }
        } else {
          if (!other.orderStyle_.isEmpty()) {
            if (orderStyleBuilder_.isEmpty()) {
              orderStyleBuilder_.dispose();
              orderStyleBuilder_ = null;
              orderStyle_ = other.orderStyle_;
              bitField0_ = (bitField0_ & ~0x00000002);
              orderStyleBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrderStyleFieldBuilder() : null;
            } else {
              orderStyleBuilder_.addAllMessages(other.orderStyle_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrderItemSn()) {
          
          return false;
        }
        for (int i = 0; i < getOrderStyleCount(); i++) {
          if (!getOrderStyle(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OrderStyleFileInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OrderStyleFileInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string order_item_sn = 1;
      private Object orderItemSn_ = "";
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public boolean hasOrderItemSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public String getOrderItemSn() {
        Object ref = orderItemSn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          orderItemSn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderItemSnBytes() {
        Object ref = orderItemSn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderItemSn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public Builder setOrderItemSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderItemSn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public Builder clearOrderItemSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderItemSn_ = getDefaultInstance().getOrderItemSn();
        onChanged();
        return this;
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public Builder setOrderItemSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderItemSn_ = value;
        onChanged();
        return this;
      }

      // repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;
      private java.util.List<StyleFile> orderStyle_ =
        java.util.Collections.emptyList();
      private void ensureOrderStyleIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          orderStyle_ = new java.util.ArrayList<StyleFile>(orderStyle_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          StyleFile, StyleFile.Builder, StyleFileOrBuilder> orderStyleBuilder_;

      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public java.util.List<StyleFile> getOrderStyleList() {
        if (orderStyleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderStyle_);
        } else {
          return orderStyleBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public int getOrderStyleCount() {
        if (orderStyleBuilder_ == null) {
          return orderStyle_.size();
        } else {
          return orderStyleBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public StyleFile getOrderStyle(int index) {
        if (orderStyleBuilder_ == null) {
          return orderStyle_.get(index);
        } else {
          return orderStyleBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder setOrderStyle(
          int index, StyleFile value) {
        if (orderStyleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderStyleIsMutable();
          orderStyle_.set(index, value);
          onChanged();
        } else {
          orderStyleBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder setOrderStyle(
          int index, StyleFile.Builder builderForValue) {
        if (orderStyleBuilder_ == null) {
          ensureOrderStyleIsMutable();
          orderStyle_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderStyleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder addOrderStyle(StyleFile value) {
        if (orderStyleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderStyleIsMutable();
          orderStyle_.add(value);
          onChanged();
        } else {
          orderStyleBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder addOrderStyle(
          int index, StyleFile value) {
        if (orderStyleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderStyleIsMutable();
          orderStyle_.add(index, value);
          onChanged();
        } else {
          orderStyleBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder addOrderStyle(
          StyleFile.Builder builderForValue) {
        if (orderStyleBuilder_ == null) {
          ensureOrderStyleIsMutable();
          orderStyle_.add(builderForValue.build());
          onChanged();
        } else {
          orderStyleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder addOrderStyle(
          int index, StyleFile.Builder builderForValue) {
        if (orderStyleBuilder_ == null) {
          ensureOrderStyleIsMutable();
          orderStyle_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderStyleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder addAllOrderStyle(
          Iterable<? extends StyleFile> values) {
        if (orderStyleBuilder_ == null) {
          ensureOrderStyleIsMutable();
          super.addAll(values, orderStyle_);
          onChanged();
        } else {
          orderStyleBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder clearOrderStyle() {
        if (orderStyleBuilder_ == null) {
          orderStyle_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          orderStyleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public Builder removeOrderStyle(int index) {
        if (orderStyleBuilder_ == null) {
          ensureOrderStyleIsMutable();
          orderStyle_.remove(index);
          onChanged();
        } else {
          orderStyleBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public StyleFile.Builder getOrderStyleBuilder(
          int index) {
        return getOrderStyleFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public StyleFileOrBuilder getOrderStyleOrBuilder(
          int index) {
        if (orderStyleBuilder_ == null) {
          return orderStyle_.get(index);  } else {
          return orderStyleBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public java.util.List<? extends StyleFileOrBuilder>
           getOrderStyleOrBuilderList() {
        if (orderStyleBuilder_ != null) {
          return orderStyleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderStyle_);
        }
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public StyleFile.Builder addOrderStyleBuilder() {
        return getOrderStyleFieldBuilder().addBuilder(
            StyleFile.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public StyleFile.Builder addOrderStyleBuilder(
          int index) {
        return getOrderStyleFieldBuilder().addBuilder(
            index, StyleFile.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderStyleFileInfo.StyleFile orderStyle = 2;</code>
       *
       * <pre>
       *款式文件
       * </pre>
       */
      public java.util.List<StyleFile.Builder>
           getOrderStyleBuilderList() {
        return getOrderStyleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          StyleFile, StyleFile.Builder, StyleFileOrBuilder>
          getOrderStyleFieldBuilder() {
        if (orderStyleBuilder_ == null) {
          orderStyleBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              StyleFile, StyleFile.Builder, StyleFileOrBuilder>(
                  orderStyle_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          orderStyle_ = null;
        }
        return orderStyleBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OrderStyleFileInfo)
    }

    static {
      defaultInstance = new OrderStyleFileInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OrderStyleFileInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderStyleFileInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderStyleFileInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderStyleFileInfo_StyleFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderStyleFileInfo_StyleFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035ProtoOrderStyleFileInfo.proto\"\363\001\n\022Orde" +
      "rStyleFileInfo\022\025\n\rorder_item_sn\030\001 \002(\t\0221\n" +
      "\norderStyle\030\002 \003(\0132\035.OrderStyleFileInfo.S" +
      "tyleFile\032\222\001\n\tStyleFile\022\022\n\nstyle_code\030\001 \002" +
      "(\t\022\025\n\rmaterial_code\030\002 \002(\t\022\017\n\007breadth\030\003 \002" +
      "(\002\022\020\n\010quantity\030\004 \002(\005\022\024\n\004unit\030\005 \002(\0162\006.EUn" +
      "it\022\017\n\007acreage\030\006 \002(\002\022\020\n\010plt_path\030\007 \002(\t*.\n" +
      "\005EUnit\022\013\n\007EUnit_m\020\000\022\013\n\007EUnit_g\020\001\022\013\n\007EUni" +
      "t_l\020\002B,\n\021com.kingthy.protoB\027ProtoOrderSt" +
      "yleFileInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OrderStyleFileInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OrderStyleFileInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderStyleFileInfo_descriptor,
              new String[] { "OrderItemSn", "OrderStyle", });
          internal_static_OrderStyleFileInfo_StyleFile_descriptor =
            internal_static_OrderStyleFileInfo_descriptor.getNestedTypes().get(0);
          internal_static_OrderStyleFileInfo_StyleFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderStyleFileInfo_StyleFile_descriptor,
              new String[] { "StyleCode", "MaterialCode", "Breadth", "Quantity", "Unit", "Acreage", "PltPath", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
