// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoOrderStitchingInfo.proto

package com.kingthy.proto;

public final class ProtoOrderStitchingInfo {
  private ProtoOrderStitchingInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code EUnit}
   */
  public enum EUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EUnit_m = 0;</code>
     *
     * <pre>
     *米
     * </pre>
     */
    EUnit_m(0, 0),
    /**
     * <code>EUnit_g = 1;</code>
     *
     * <pre>
     *个
     * </pre>
     */
    EUnit_g(1, 1),
    /**
     * <code>EUnit_l = 2;</code>
     *
     * <pre>
     *粒
     * </pre>
     */
    EUnit_l(2, 2),
    ;

    /**
     * <code>EUnit_m = 0;</code>
     *
     * <pre>
     *米
     * </pre>
     */
    public static final int EUnit_m_VALUE = 0;
    /**
     * <code>EUnit_g = 1;</code>
     *
     * <pre>
     *个
     * </pre>
     */
    public static final int EUnit_g_VALUE = 1;
    /**
     * <code>EUnit_l = 2;</code>
     *
     * <pre>
     *粒
     * </pre>
     */
    public static final int EUnit_l_VALUE = 2;


    public final int getNumber() { return value; }

    public static EUnit valueOf(int value) {
      switch (value) {
        case 0: return EUnit_m;
        case 1: return EUnit_g;
        case 2: return EUnit_l;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EUnit>() {
            public EUnit findValueByNumber(int number) {
              return EUnit.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtoOrderStitchingInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final EUnit[] VALUES = values();

    public static EUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EUnit)
  }

  public interface OrderStitchingInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string order_item_sn = 1;
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    boolean hasOrderItemSn();
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    String getOrderItemSn();
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderItemSnBytes();

    // repeated .OrderStitchingInfo.Stitching stitching = 2;
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    java.util.List<OrderStitchingInfo.Stitching>
        getStitchingList();
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    OrderStitchingInfo.Stitching getStitching(int index);
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    int getStitchingCount();
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    java.util.List<? extends OrderStitchingInfo.StitchingOrBuilder>
        getStitchingOrBuilderList();
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    OrderStitchingInfo.StitchingOrBuilder getStitchingOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code OrderStitchingInfo}
   *
   * <pre>
   *缝合关系接口表
   * </pre>
   */
  public static final class OrderStitchingInfo extends
      com.google.protobuf.GeneratedMessage
      implements OrderStitchingInfoOrBuilder {
    // Use OrderStitchingInfo.newBuilder() to construct.
    private OrderStitchingInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderStitchingInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderStitchingInfo defaultInstance;
    public static OrderStitchingInfo getDefaultInstance() {
      return defaultInstance;
    }

    public OrderStitchingInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderStitchingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orderItemSn_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                stitching_ = new java.util.ArrayList<Stitching>();
                mutable_bitField0_ |= 0x00000002;
              }
              stitching_.add(input.readMessage(Stitching.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          stitching_ = java.util.Collections.unmodifiableList(stitching_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderStitchingInfo.class, Builder.class);
    }

    public static com.google.protobuf.Parser<OrderStitchingInfo> PARSER =
        new com.google.protobuf.AbstractParser<OrderStitchingInfo>() {
      public OrderStitchingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderStitchingInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OrderStitchingInfo> getParserForType() {
      return PARSER;
    }

    public interface StitchingOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string piece1_code = 1;
      /**
       * <code>required string piece1_code = 1;</code>
       *
       * <pre>
       *板片1编码
       * </pre>
       */
      boolean hasPiece1Code();
      /**
       * <code>required string piece1_code = 1;</code>
       *
       * <pre>
       *板片1编码
       * </pre>
       */
      String getPiece1Code();
      /**
       * <code>required string piece1_code = 1;</code>
       *
       * <pre>
       *板片1编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getPiece1CodeBytes();

      // required string piece2_code = 2;
      /**
       * <code>required string piece2_code = 2;</code>
       *
       * <pre>
       *板片2编码
       * </pre>
       */
      boolean hasPiece2Code();
      /**
       * <code>required string piece2_code = 2;</code>
       *
       * <pre>
       *板片2编码
       * </pre>
       */
      String getPiece2Code();
      /**
       * <code>required string piece2_code = 2;</code>
       *
       * <pre>
       *板片2编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getPiece2CodeBytes();

      // required string edge1_code = 3;
      /**
       * <code>required string edge1_code = 3;</code>
       *
       * <pre>
       *边1编码
       * </pre>
       */
      boolean hasEdge1Code();
      /**
       * <code>required string edge1_code = 3;</code>
       *
       * <pre>
       *边1编码
       * </pre>
       */
      String getEdge1Code();
      /**
       * <code>required string edge1_code = 3;</code>
       *
       * <pre>
       *边1编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getEdge1CodeBytes();

      // required string edge2_code = 4;
      /**
       * <code>required string edge2_code = 4;</code>
       *
       * <pre>
       *边2编码
       * </pre>
       */
      boolean hasEdge2Code();
      /**
       * <code>required string edge2_code = 4;</code>
       *
       * <pre>
       *边2编码
       * </pre>
       */
      String getEdge2Code();
      /**
       * <code>required string edge2_code = 4;</code>
       *
       * <pre>
       *边2编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getEdge2CodeBytes();

      // required float edge1_len = 5;
      /**
       * <code>required float edge1_len = 5;</code>
       *
       * <pre>
       *边1长度
       * </pre>
       */
      boolean hasEdge1Len();
      /**
       * <code>required float edge1_len = 5;</code>
       *
       * <pre>
       *边1长度
       * </pre>
       */
      float getEdge1Len();

      // required float edge2_len = 6;
      /**
       * <code>required float edge2_len = 6;</code>
       *
       * <pre>
       *边2长度
       * </pre>
       */
      boolean hasEdge2Len();
      /**
       * <code>required float edge2_len = 6;</code>
       *
       * <pre>
       *边2长度
       * </pre>
       */
      float getEdge2Len();

      // required string SeamType = 7;
      /**
       * <code>required string SeamType = 7;</code>
       *
       * <pre>
       *缝合工艺编码
       * </pre>
       */
      boolean hasSeamType();
      /**
       * <code>required string SeamType = 7;</code>
       *
       * <pre>
       *缝合工艺编码
       * </pre>
       */
      String getSeamType();
      /**
       * <code>required string SeamType = 7;</code>
       *
       * <pre>
       *缝合工艺编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getSeamTypeBytes();

      // required string style_code = 8;
      /**
       * <code>required string style_code = 8;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      boolean hasStyleCode();
      /**
       * <code>required string style_code = 8;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      String getStyleCode();
      /**
       * <code>required string style_code = 8;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      com.google.protobuf.ByteString
          getStyleCodeBytes();
    }
    /**
     * Protobuf type {@code OrderStitchingInfo.Stitching}
     */
    public static final class Stitching extends
        com.google.protobuf.GeneratedMessage
        implements StitchingOrBuilder {
      // Use Stitching.newBuilder() to construct.
      private Stitching(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Stitching(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Stitching defaultInstance;
      public static Stitching getDefaultInstance() {
        return defaultInstance;
      }

      public Stitching getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Stitching(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                piece1Code_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                piece2Code_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                edge1Code_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                edge2Code_ = input.readBytes();
                break;
              }
              case 45: {
                bitField0_ |= 0x00000010;
                edge1Len_ = input.readFloat();
                break;
              }
              case 53: {
                bitField0_ |= 0x00000020;
                edge2Len_ = input.readFloat();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                seamType_ = input.readBytes();
                break;
              }
              case 66: {
                bitField0_ |= 0x00000080;
                styleCode_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_Stitching_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_Stitching_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Stitching.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Stitching> PARSER =
          new com.google.protobuf.AbstractParser<Stitching>() {
        public Stitching parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Stitching(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Stitching> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string piece1_code = 1;
      public static final int PIECE1_CODE_FIELD_NUMBER = 1;
      private Object piece1Code_;
      /**
       * <code>required string piece1_code = 1;</code>
       *
       * <pre>
       *板片1编码
       * </pre>
       */
      public boolean hasPiece1Code() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string piece1_code = 1;</code>
       *
       * <pre>
       *板片1编码
       * </pre>
       */
      public String getPiece1Code() {
        Object ref = piece1Code_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            piece1Code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string piece1_code = 1;</code>
       *
       * <pre>
       *板片1编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPiece1CodeBytes() {
        Object ref = piece1Code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          piece1Code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string piece2_code = 2;
      public static final int PIECE2_CODE_FIELD_NUMBER = 2;
      private Object piece2Code_;
      /**
       * <code>required string piece2_code = 2;</code>
       *
       * <pre>
       *板片2编码
       * </pre>
       */
      public boolean hasPiece2Code() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string piece2_code = 2;</code>
       *
       * <pre>
       *板片2编码
       * </pre>
       */
      public String getPiece2Code() {
        Object ref = piece2Code_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            piece2Code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string piece2_code = 2;</code>
       *
       * <pre>
       *板片2编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPiece2CodeBytes() {
        Object ref = piece2Code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          piece2Code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string edge1_code = 3;
      public static final int EDGE1_CODE_FIELD_NUMBER = 3;
      private Object edge1Code_;
      /**
       * <code>required string edge1_code = 3;</code>
       *
       * <pre>
       *边1编码
       * </pre>
       */
      public boolean hasEdge1Code() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string edge1_code = 3;</code>
       *
       * <pre>
       *边1编码
       * </pre>
       */
      public String getEdge1Code() {
        Object ref = edge1Code_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            edge1Code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string edge1_code = 3;</code>
       *
       * <pre>
       *边1编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEdge1CodeBytes() {
        Object ref = edge1Code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          edge1Code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string edge2_code = 4;
      public static final int EDGE2_CODE_FIELD_NUMBER = 4;
      private Object edge2Code_;
      /**
       * <code>required string edge2_code = 4;</code>
       *
       * <pre>
       *边2编码
       * </pre>
       */
      public boolean hasEdge2Code() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string edge2_code = 4;</code>
       *
       * <pre>
       *边2编码
       * </pre>
       */
      public String getEdge2Code() {
        Object ref = edge2Code_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            edge2Code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string edge2_code = 4;</code>
       *
       * <pre>
       *边2编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEdge2CodeBytes() {
        Object ref = edge2Code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          edge2Code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required float edge1_len = 5;
      public static final int EDGE1_LEN_FIELD_NUMBER = 5;
      private float edge1Len_;
      /**
       * <code>required float edge1_len = 5;</code>
       *
       * <pre>
       *边1长度
       * </pre>
       */
      public boolean hasEdge1Len() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float edge1_len = 5;</code>
       *
       * <pre>
       *边1长度
       * </pre>
       */
      public float getEdge1Len() {
        return edge1Len_;
      }

      // required float edge2_len = 6;
      public static final int EDGE2_LEN_FIELD_NUMBER = 6;
      private float edge2Len_;
      /**
       * <code>required float edge2_len = 6;</code>
       *
       * <pre>
       *边2长度
       * </pre>
       */
      public boolean hasEdge2Len() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float edge2_len = 6;</code>
       *
       * <pre>
       *边2长度
       * </pre>
       */
      public float getEdge2Len() {
        return edge2Len_;
      }

      // required string SeamType = 7;
      public static final int SEAMTYPE_FIELD_NUMBER = 7;
      private Object seamType_;
      /**
       * <code>required string SeamType = 7;</code>
       *
       * <pre>
       *缝合工艺编码
       * </pre>
       */
      public boolean hasSeamType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string SeamType = 7;</code>
       *
       * <pre>
       *缝合工艺编码
       * </pre>
       */
      public String getSeamType() {
        Object ref = seamType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            seamType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string SeamType = 7;</code>
       *
       * <pre>
       *缝合工艺编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSeamTypeBytes() {
        Object ref = seamType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          seamType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string style_code = 8;
      public static final int STYLE_CODE_FIELD_NUMBER = 8;
      private Object styleCode_;
      /**
       * <code>required string style_code = 8;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      public boolean hasStyleCode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string style_code = 8;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      public String getStyleCode() {
        Object ref = styleCode_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            styleCode_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string style_code = 8;</code>
       *
       * <pre>
       *款式编码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStyleCodeBytes() {
        Object ref = styleCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          styleCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        piece1Code_ = "";
        piece2Code_ = "";
        edge1Code_ = "";
        edge2Code_ = "";
        edge1Len_ = 0F;
        edge2Len_ = 0F;
        seamType_ = "";
        styleCode_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPiece1Code()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPiece2Code()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEdge1Code()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEdge2Code()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEdge1Len()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEdge2Len()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSeamType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStyleCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getPiece1CodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getPiece2CodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getEdge1CodeBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getEdge2CodeBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeFloat(5, edge1Len_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeFloat(6, edge2Len_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, getSeamTypeBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeBytes(8, getStyleCodeBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getPiece1CodeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getPiece2CodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getEdge1CodeBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getEdge2CodeBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(5, edge1Len_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(6, edge2Len_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, getSeamTypeBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(8, getStyleCodeBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Stitching parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Stitching parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Stitching parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Stitching parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Stitching parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Stitching parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Stitching parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Stitching parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Stitching parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Stitching parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Stitching prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code OrderStitchingInfo.Stitching}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements StitchingOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_Stitching_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_Stitching_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Stitching.class, Builder.class);
        }

        // Construct using com.kingthy.proto.ProtoOrderStitchingInfo.OrderStitchingInfo.Stitching.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          piece1Code_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          piece2Code_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          edge1Code_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          edge2Code_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          edge1Len_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000010);
          edge2Len_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000020);
          seamType_ = "";
          bitField0_ = (bitField0_ & ~0x00000040);
          styleCode_ = "";
          bitField0_ = (bitField0_ & ~0x00000080);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_Stitching_descriptor;
        }

        public Stitching getDefaultInstanceForType() {
          return Stitching.getDefaultInstance();
        }

        public Stitching build() {
          Stitching result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Stitching buildPartial() {
          Stitching result = new Stitching(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.piece1Code_ = piece1Code_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.piece2Code_ = piece2Code_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.edge1Code_ = edge1Code_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.edge2Code_ = edge2Code_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.edge1Len_ = edge1Len_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.edge2Len_ = edge2Len_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.seamType_ = seamType_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.styleCode_ = styleCode_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Stitching) {
            return mergeFrom((Stitching)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Stitching other) {
          if (other == Stitching.getDefaultInstance()) return this;
          if (other.hasPiece1Code()) {
            bitField0_ |= 0x00000001;
            piece1Code_ = other.piece1Code_;
            onChanged();
          }
          if (other.hasPiece2Code()) {
            bitField0_ |= 0x00000002;
            piece2Code_ = other.piece2Code_;
            onChanged();
          }
          if (other.hasEdge1Code()) {
            bitField0_ |= 0x00000004;
            edge1Code_ = other.edge1Code_;
            onChanged();
          }
          if (other.hasEdge2Code()) {
            bitField0_ |= 0x00000008;
            edge2Code_ = other.edge2Code_;
            onChanged();
          }
          if (other.hasEdge1Len()) {
            setEdge1Len(other.getEdge1Len());
          }
          if (other.hasEdge2Len()) {
            setEdge2Len(other.getEdge2Len());
          }
          if (other.hasSeamType()) {
            bitField0_ |= 0x00000040;
            seamType_ = other.seamType_;
            onChanged();
          }
          if (other.hasStyleCode()) {
            bitField0_ |= 0x00000080;
            styleCode_ = other.styleCode_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPiece1Code()) {
            
            return false;
          }
          if (!hasPiece2Code()) {
            
            return false;
          }
          if (!hasEdge1Code()) {
            
            return false;
          }
          if (!hasEdge2Code()) {
            
            return false;
          }
          if (!hasEdge1Len()) {
            
            return false;
          }
          if (!hasEdge2Len()) {
            
            return false;
          }
          if (!hasSeamType()) {
            
            return false;
          }
          if (!hasStyleCode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Stitching parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Stitching) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string piece1_code = 1;
        private Object piece1Code_ = "";
        /**
         * <code>required string piece1_code = 1;</code>
         *
         * <pre>
         *板片1编码
         * </pre>
         */
        public boolean hasPiece1Code() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string piece1_code = 1;</code>
         *
         * <pre>
         *板片1编码
         * </pre>
         */
        public String getPiece1Code() {
          Object ref = piece1Code_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            piece1Code_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string piece1_code = 1;</code>
         *
         * <pre>
         *板片1编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getPiece1CodeBytes() {
          Object ref = piece1Code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            piece1Code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string piece1_code = 1;</code>
         *
         * <pre>
         *板片1编码
         * </pre>
         */
        public Builder setPiece1Code(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          piece1Code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string piece1_code = 1;</code>
         *
         * <pre>
         *板片1编码
         * </pre>
         */
        public Builder clearPiece1Code() {
          bitField0_ = (bitField0_ & ~0x00000001);
          piece1Code_ = getDefaultInstance().getPiece1Code();
          onChanged();
          return this;
        }
        /**
         * <code>required string piece1_code = 1;</code>
         *
         * <pre>
         *板片1编码
         * </pre>
         */
        public Builder setPiece1CodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          piece1Code_ = value;
          onChanged();
          return this;
        }

        // required string piece2_code = 2;
        private Object piece2Code_ = "";
        /**
         * <code>required string piece2_code = 2;</code>
         *
         * <pre>
         *板片2编码
         * </pre>
         */
        public boolean hasPiece2Code() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string piece2_code = 2;</code>
         *
         * <pre>
         *板片2编码
         * </pre>
         */
        public String getPiece2Code() {
          Object ref = piece2Code_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            piece2Code_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string piece2_code = 2;</code>
         *
         * <pre>
         *板片2编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getPiece2CodeBytes() {
          Object ref = piece2Code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            piece2Code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string piece2_code = 2;</code>
         *
         * <pre>
         *板片2编码
         * </pre>
         */
        public Builder setPiece2Code(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          piece2Code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string piece2_code = 2;</code>
         *
         * <pre>
         *板片2编码
         * </pre>
         */
        public Builder clearPiece2Code() {
          bitField0_ = (bitField0_ & ~0x00000002);
          piece2Code_ = getDefaultInstance().getPiece2Code();
          onChanged();
          return this;
        }
        /**
         * <code>required string piece2_code = 2;</code>
         *
         * <pre>
         *板片2编码
         * </pre>
         */
        public Builder setPiece2CodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          piece2Code_ = value;
          onChanged();
          return this;
        }

        // required string edge1_code = 3;
        private Object edge1Code_ = "";
        /**
         * <code>required string edge1_code = 3;</code>
         *
         * <pre>
         *边1编码
         * </pre>
         */
        public boolean hasEdge1Code() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string edge1_code = 3;</code>
         *
         * <pre>
         *边1编码
         * </pre>
         */
        public String getEdge1Code() {
          Object ref = edge1Code_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            edge1Code_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string edge1_code = 3;</code>
         *
         * <pre>
         *边1编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getEdge1CodeBytes() {
          Object ref = edge1Code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            edge1Code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string edge1_code = 3;</code>
         *
         * <pre>
         *边1编码
         * </pre>
         */
        public Builder setEdge1Code(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          edge1Code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string edge1_code = 3;</code>
         *
         * <pre>
         *边1编码
         * </pre>
         */
        public Builder clearEdge1Code() {
          bitField0_ = (bitField0_ & ~0x00000004);
          edge1Code_ = getDefaultInstance().getEdge1Code();
          onChanged();
          return this;
        }
        /**
         * <code>required string edge1_code = 3;</code>
         *
         * <pre>
         *边1编码
         * </pre>
         */
        public Builder setEdge1CodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          edge1Code_ = value;
          onChanged();
          return this;
        }

        // required string edge2_code = 4;
        private Object edge2Code_ = "";
        /**
         * <code>required string edge2_code = 4;</code>
         *
         * <pre>
         *边2编码
         * </pre>
         */
        public boolean hasEdge2Code() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required string edge2_code = 4;</code>
         *
         * <pre>
         *边2编码
         * </pre>
         */
        public String getEdge2Code() {
          Object ref = edge2Code_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            edge2Code_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string edge2_code = 4;</code>
         *
         * <pre>
         *边2编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getEdge2CodeBytes() {
          Object ref = edge2Code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            edge2Code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string edge2_code = 4;</code>
         *
         * <pre>
         *边2编码
         * </pre>
         */
        public Builder setEdge2Code(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          edge2Code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string edge2_code = 4;</code>
         *
         * <pre>
         *边2编码
         * </pre>
         */
        public Builder clearEdge2Code() {
          bitField0_ = (bitField0_ & ~0x00000008);
          edge2Code_ = getDefaultInstance().getEdge2Code();
          onChanged();
          return this;
        }
        /**
         * <code>required string edge2_code = 4;</code>
         *
         * <pre>
         *边2编码
         * </pre>
         */
        public Builder setEdge2CodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          edge2Code_ = value;
          onChanged();
          return this;
        }

        // required float edge1_len = 5;
        private float edge1Len_ ;
        /**
         * <code>required float edge1_len = 5;</code>
         *
         * <pre>
         *边1长度
         * </pre>
         */
        public boolean hasEdge1Len() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required float edge1_len = 5;</code>
         *
         * <pre>
         *边1长度
         * </pre>
         */
        public float getEdge1Len() {
          return edge1Len_;
        }
        /**
         * <code>required float edge1_len = 5;</code>
         *
         * <pre>
         *边1长度
         * </pre>
         */
        public Builder setEdge1Len(float value) {
          bitField0_ |= 0x00000010;
          edge1Len_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float edge1_len = 5;</code>
         *
         * <pre>
         *边1长度
         * </pre>
         */
        public Builder clearEdge1Len() {
          bitField0_ = (bitField0_ & ~0x00000010);
          edge1Len_ = 0F;
          onChanged();
          return this;
        }

        // required float edge2_len = 6;
        private float edge2Len_ ;
        /**
         * <code>required float edge2_len = 6;</code>
         *
         * <pre>
         *边2长度
         * </pre>
         */
        public boolean hasEdge2Len() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required float edge2_len = 6;</code>
         *
         * <pre>
         *边2长度
         * </pre>
         */
        public float getEdge2Len() {
          return edge2Len_;
        }
        /**
         * <code>required float edge2_len = 6;</code>
         *
         * <pre>
         *边2长度
         * </pre>
         */
        public Builder setEdge2Len(float value) {
          bitField0_ |= 0x00000020;
          edge2Len_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float edge2_len = 6;</code>
         *
         * <pre>
         *边2长度
         * </pre>
         */
        public Builder clearEdge2Len() {
          bitField0_ = (bitField0_ & ~0x00000020);
          edge2Len_ = 0F;
          onChanged();
          return this;
        }

        // required string SeamType = 7;
        private Object seamType_ = "";
        /**
         * <code>required string SeamType = 7;</code>
         *
         * <pre>
         *缝合工艺编码
         * </pre>
         */
        public boolean hasSeamType() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required string SeamType = 7;</code>
         *
         * <pre>
         *缝合工艺编码
         * </pre>
         */
        public String getSeamType() {
          Object ref = seamType_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            seamType_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string SeamType = 7;</code>
         *
         * <pre>
         *缝合工艺编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getSeamTypeBytes() {
          Object ref = seamType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            seamType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string SeamType = 7;</code>
         *
         * <pre>
         *缝合工艺编码
         * </pre>
         */
        public Builder setSeamType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          seamType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string SeamType = 7;</code>
         *
         * <pre>
         *缝合工艺编码
         * </pre>
         */
        public Builder clearSeamType() {
          bitField0_ = (bitField0_ & ~0x00000040);
          seamType_ = getDefaultInstance().getSeamType();
          onChanged();
          return this;
        }
        /**
         * <code>required string SeamType = 7;</code>
         *
         * <pre>
         *缝合工艺编码
         * </pre>
         */
        public Builder setSeamTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          seamType_ = value;
          onChanged();
          return this;
        }

        // required string style_code = 8;
        private Object styleCode_ = "";
        /**
         * <code>required string style_code = 8;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public boolean hasStyleCode() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>required string style_code = 8;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public String getStyleCode() {
          Object ref = styleCode_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            styleCode_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string style_code = 8;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public com.google.protobuf.ByteString
            getStyleCodeBytes() {
          Object ref = styleCode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            styleCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string style_code = 8;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public Builder setStyleCode(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          styleCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string style_code = 8;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public Builder clearStyleCode() {
          bitField0_ = (bitField0_ & ~0x00000080);
          styleCode_ = getDefaultInstance().getStyleCode();
          onChanged();
          return this;
        }
        /**
         * <code>required string style_code = 8;</code>
         *
         * <pre>
         *款式编码
         * </pre>
         */
        public Builder setStyleCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          styleCode_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:OrderStitchingInfo.Stitching)
      }

      static {
        defaultInstance = new Stitching(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:OrderStitchingInfo.Stitching)
    }

    private int bitField0_;
    // required string order_item_sn = 1;
    public static final int ORDER_ITEM_SN_FIELD_NUMBER = 1;
    private Object orderItemSn_;
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    public boolean hasOrderItemSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    public String getOrderItemSn() {
      Object ref = orderItemSn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderItemSn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string order_item_sn = 1;</code>
     *
     * <pre>
     *子订单号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderItemSnBytes() {
      Object ref = orderItemSn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderItemSn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .OrderStitchingInfo.Stitching stitching = 2;
    public static final int STITCHING_FIELD_NUMBER = 2;
    private java.util.List<Stitching> stitching_;
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    public java.util.List<Stitching> getStitchingList() {
      return stitching_;
    }
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    public java.util.List<? extends StitchingOrBuilder>
        getStitchingOrBuilderList() {
      return stitching_;
    }
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    public int getStitchingCount() {
      return stitching_.size();
    }
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    public Stitching getStitching(int index) {
      return stitching_.get(index);
    }
    /**
     * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
     *
     * <pre>
     *缝合关系
     * </pre>
     */
    public StitchingOrBuilder getStitchingOrBuilder(
        int index) {
      return stitching_.get(index);
    }

    private void initFields() {
      orderItemSn_ = "";
      stitching_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOrderItemSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getStitchingCount(); i++) {
        if (!getStitching(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOrderItemSnBytes());
      }
      for (int i = 0; i < stitching_.size(); i++) {
        output.writeMessage(2, stitching_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderItemSnBytes());
      }
      for (int i = 0; i < stitching_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, stitching_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static OrderStitchingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderStitchingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderStitchingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderStitchingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderStitchingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OrderStitchingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static OrderStitchingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static OrderStitchingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static OrderStitchingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OrderStitchingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(OrderStitchingInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderStitchingInfo}
     *
     * <pre>
     *缝合关系接口表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OrderStitchingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderStitchingInfo.class, Builder.class);
      }

      // Construct using com.kingthy.proto.ProtoOrderStitchingInfo.OrderStitchingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStitchingFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orderItemSn_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (stitchingBuilder_ == null) {
          stitching_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          stitchingBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoOrderStitchingInfo.internal_static_OrderStitchingInfo_descriptor;
      }

      public OrderStitchingInfo getDefaultInstanceForType() {
        return OrderStitchingInfo.getDefaultInstance();
      }

      public OrderStitchingInfo build() {
        OrderStitchingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OrderStitchingInfo buildPartial() {
        OrderStitchingInfo result = new OrderStitchingInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderItemSn_ = orderItemSn_;
        if (stitchingBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            stitching_ = java.util.Collections.unmodifiableList(stitching_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.stitching_ = stitching_;
        } else {
          result.stitching_ = stitchingBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderStitchingInfo) {
          return mergeFrom((OrderStitchingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderStitchingInfo other) {
        if (other == OrderStitchingInfo.getDefaultInstance()) return this;
        if (other.hasOrderItemSn()) {
          bitField0_ |= 0x00000001;
          orderItemSn_ = other.orderItemSn_;
          onChanged();
        }
        if (stitchingBuilder_ == null) {
          if (!other.stitching_.isEmpty()) {
            if (stitching_.isEmpty()) {
              stitching_ = other.stitching_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStitchingIsMutable();
              stitching_.addAll(other.stitching_);
            }
            onChanged();
          }
        } else {
          if (!other.stitching_.isEmpty()) {
            if (stitchingBuilder_.isEmpty()) {
              stitchingBuilder_.dispose();
              stitchingBuilder_ = null;
              stitching_ = other.stitching_;
              bitField0_ = (bitField0_ & ~0x00000002);
              stitchingBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStitchingFieldBuilder() : null;
            } else {
              stitchingBuilder_.addAllMessages(other.stitching_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrderItemSn()) {
          
          return false;
        }
        for (int i = 0; i < getStitchingCount(); i++) {
          if (!getStitching(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OrderStitchingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OrderStitchingInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string order_item_sn = 1;
      private Object orderItemSn_ = "";
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public boolean hasOrderItemSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public String getOrderItemSn() {
        Object ref = orderItemSn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          orderItemSn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderItemSnBytes() {
        Object ref = orderItemSn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderItemSn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public Builder setOrderItemSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderItemSn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public Builder clearOrderItemSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderItemSn_ = getDefaultInstance().getOrderItemSn();
        onChanged();
        return this;
      }
      /**
       * <code>required string order_item_sn = 1;</code>
       *
       * <pre>
       *子订单号
       * </pre>
       */
      public Builder setOrderItemSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderItemSn_ = value;
        onChanged();
        return this;
      }

      // repeated .OrderStitchingInfo.Stitching stitching = 2;
      private java.util.List<Stitching> stitching_ =
        java.util.Collections.emptyList();
      private void ensureStitchingIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          stitching_ = new java.util.ArrayList<Stitching>(stitching_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Stitching, Stitching.Builder, StitchingOrBuilder> stitchingBuilder_;

      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public java.util.List<Stitching> getStitchingList() {
        if (stitchingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stitching_);
        } else {
          return stitchingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public int getStitchingCount() {
        if (stitchingBuilder_ == null) {
          return stitching_.size();
        } else {
          return stitchingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Stitching getStitching(int index) {
        if (stitchingBuilder_ == null) {
          return stitching_.get(index);
        } else {
          return stitchingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder setStitching(
          int index, Stitching value) {
        if (stitchingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStitchingIsMutable();
          stitching_.set(index, value);
          onChanged();
        } else {
          stitchingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder setStitching(
          int index, Stitching.Builder builderForValue) {
        if (stitchingBuilder_ == null) {
          ensureStitchingIsMutable();
          stitching_.set(index, builderForValue.build());
          onChanged();
        } else {
          stitchingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder addStitching(Stitching value) {
        if (stitchingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStitchingIsMutable();
          stitching_.add(value);
          onChanged();
        } else {
          stitchingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder addStitching(
          int index, Stitching value) {
        if (stitchingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStitchingIsMutable();
          stitching_.add(index, value);
          onChanged();
        } else {
          stitchingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder addStitching(
          Stitching.Builder builderForValue) {
        if (stitchingBuilder_ == null) {
          ensureStitchingIsMutable();
          stitching_.add(builderForValue.build());
          onChanged();
        } else {
          stitchingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder addStitching(
          int index, Stitching.Builder builderForValue) {
        if (stitchingBuilder_ == null) {
          ensureStitchingIsMutable();
          stitching_.add(index, builderForValue.build());
          onChanged();
        } else {
          stitchingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder addAllStitching(
          Iterable<? extends Stitching> values) {
        if (stitchingBuilder_ == null) {
          ensureStitchingIsMutable();
          super.addAll(values, stitching_);
          onChanged();
        } else {
          stitchingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder clearStitching() {
        if (stitchingBuilder_ == null) {
          stitching_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          stitchingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Builder removeStitching(int index) {
        if (stitchingBuilder_ == null) {
          ensureStitchingIsMutable();
          stitching_.remove(index);
          onChanged();
        } else {
          stitchingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Stitching.Builder getStitchingBuilder(
          int index) {
        return getStitchingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public StitchingOrBuilder getStitchingOrBuilder(
          int index) {
        if (stitchingBuilder_ == null) {
          return stitching_.get(index);  } else {
          return stitchingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public java.util.List<? extends StitchingOrBuilder>
           getStitchingOrBuilderList() {
        if (stitchingBuilder_ != null) {
          return stitchingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stitching_);
        }
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Stitching.Builder addStitchingBuilder() {
        return getStitchingFieldBuilder().addBuilder(
            Stitching.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public Stitching.Builder addStitchingBuilder(
          int index) {
        return getStitchingFieldBuilder().addBuilder(
            index, Stitching.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderStitchingInfo.Stitching stitching = 2;</code>
       *
       * <pre>
       *缝合关系
       * </pre>
       */
      public java.util.List<Stitching.Builder>
           getStitchingBuilderList() {
        return getStitchingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Stitching, Stitching.Builder, StitchingOrBuilder>
          getStitchingFieldBuilder() {
        if (stitchingBuilder_ == null) {
          stitchingBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Stitching, Stitching.Builder, StitchingOrBuilder>(
                  stitching_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          stitching_ = null;
        }
        return stitchingBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OrderStitchingInfo)
    }

    static {
      defaultInstance = new OrderStitchingInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OrderStitchingInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderStitchingInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderStitchingInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderStitchingInfo_Stitching_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderStitchingInfo_Stitching_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035ProtoOrderStitchingInfo.proto\"\211\002\n\022Orde" +
      "rStitchingInfo\022\025\n\rorder_item_sn\030\001 \002(\t\0220\n" +
      "\tstitching\030\002 \003(\0132\035.OrderStitchingInfo.St" +
      "itching\032\251\001\n\tStitching\022\023\n\013piece1_code\030\001 \002" +
      "(\t\022\023\n\013piece2_code\030\002 \002(\t\022\022\n\nedge1_code\030\003 " +
      "\002(\t\022\022\n\nedge2_code\030\004 \002(\t\022\021\n\tedge1_len\030\005 \002" +
      "(\002\022\021\n\tedge2_len\030\006 \002(\002\022\020\n\010SeamType\030\007 \002(\t\022" +
      "\022\n\nstyle_code\030\010 \002(\t*.\n\005EUnit\022\013\n\007EUnit_m\020" +
      "\000\022\013\n\007EUnit_g\020\001\022\013\n\007EUnit_l\020\002B,\n\021com.kingt" +
      "hy.protoB\027ProtoOrderStitchingInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OrderStitchingInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OrderStitchingInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderStitchingInfo_descriptor,
              new String[] { "OrderItemSn", "Stitching", });
          internal_static_OrderStitchingInfo_Stitching_descriptor =
            internal_static_OrderStitchingInfo_descriptor.getNestedTypes().get(0);
          internal_static_OrderStitchingInfo_Stitching_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderStitchingInfo_Stitching_descriptor,
              new String[] { "Piece1Code", "Piece2Code", "Edge1Code", "Edge2Code", "Edge1Len", "Edge2Len", "SeamType", "StyleCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
